### ISSUE TITLE
Permission error due to bind mount

### ISSUE THREAD

**Issue by HexPandaa** [Wonderfall/docker-rtorrent#1]
Hi, thanks for sharing this new version of you rtorrent-flood container stack with us.

It looks like I have a problem starting the new version.

When the data and config volumes are mounted, they are owned by root inside the container.
So when the container is started, these volumes are not writable by the user executing the entrypoint (1200:1200 in my case), and thus rtorrent and flood cannot write their default files.

I created the folders beforehand, with the right uid:gid pair. The only way I found to make the volumes writable is to `chmod o+rwx`  it before starting the container, wich doesn't seem like a good idea to me.

Do you have any more insight about how you start your stack ?

P.S.: I read the [issue thread](https://github.com/jesec/flood/discussions/120)  on the jesec repo but it doesn't seem to help me as I'm doing what others are.

Thanks for your help!

**Comment by Cediddi** [comment]
I can second that as well. Just tried to run the project, it doesn't. I'm mostly using linuxserver.io containers, I wanted to give this a shot. I've also tried to run with root privileges.

**Comment by Wonderfall** [comment]
Did you make sure:
- You're running as the same user for both rtorrent and flood
- `/path/to/rtorrent` and `/path/to/media/torrents` are both owned by this user (recursively)

If yes, can you share me your compose and your `docker logs`? I can't say I've had permission issues with the stack, but the way permissions are handled is very different from my previous `rtorrent-flood` image or linuxserver images. Both start as root and set the permissions for you, that isn't the case for this image (and probably the Flood one too). The idea is that you set permissions once and you're done with it. :)

**Comment by Wonderfall** [comment]
I can't seem to reproduce in a VM:
- I make a `/path/to/rtorrent` folder on the host, owned by 1200:1200
- I put there the `.rtorrent.rc`
- Then I start the container:

```
docker run -ti --rm --user 1200:1200 -v $PWD:/config ghcr.io/wonderfall/rtorrent:0.9.8
```

It works as expected. But of course if UID/GID doesn't match, it will throw you an error. What does `ls -la` look like in your `/path/to/rtorrent`?

**Comment by bastienwirtz** [comment]
Upgraded to the new image ( :heart: ) yesterday, haven't got any issue with bind mount (or anything).

**Comment by HexPandaa** [comment]
Sorry for the delay, I was on vacations for a few weeks and I'm back, I'll look into the new version, thanks!

**Comment by HexPandaa** [comment]
It seems like the new version did not resolve the issue.




@Wonderfall 
> I can't seem to reproduce in a VM:
> 
>     * I make a `/path/to/rtorrent` folder on the host, owned by 1200:1200
> 
>     * I put there the `.rtorrent.rc`
> 
>     * Then I start the container:
> 
> 
> ```
> docker run -ti --rm --user 1200:1200 -v $PWD:/config ghcr.io/wonderfall/rtorrent:0.9.8
> ```
> 
> It works as expected. But of course if UID/GID doesn't match, it will throw you an error. What does `ls -la` look like in your `/path/to/rtorrent`?

```bash
> mkdir data config
> cp .rtorrent.rc config
> docker compose up 
```

```
[+] Running 2/2
 ⠿ Container flood     Recreated                                                                                                  0.7s
 ⠿ Container rtorrent  Recreated                                                                                                  0.6s
Attaching to flood, rtorrent
rtorrent  | Error opening terminal: unknown.
rtorrent  | Forgot to enable daemon mode?
rtorrent  | To enable it, use "-o system.daemon.set=true".
rtorrent exited with code 1
flood     | Failed to access runtime directory
rtorrent exited with code 1
flood exited with code 1
rtorrent exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
[+] Running 2/2
 ⠿ Container flood     Stopped                                                                                                    1.2s
 ⠿ Container rtorrent  Stopped                                                                                                    1.1s
canceled
```

My docker-compose.yml :
```yaml
networks:
  rtorrent_network:

services:
  rtorrent:
    image: ghcr.io/wonderfall/rtorrent:0.9.8
    container_name: rtorrent
    user: 1200:1200
    restart: unless-stopped
    # cpus: 8
    # mem_limit: 14g
    # pids_limit: 1024
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      - HOME=/config
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 49184:49184
      - 49184:49184/udp
    networks:
      - rtorrent_network

  flood:
    image: jesec/flood:4.7.0
    container_name: flood
    user: 1200:1200
    restart: unless-stopped
    # cpus: 2
    # mem_limit: 4g
    # pids_limit: 1024
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    command: --port 3000 --allowedpath /data/torrents
    environment:
      - HOME=/config
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      - rtorrent_network

```

When building the containers in debug and attaching to them, I can see the user inside the container don't have the rights to create directories or files inside the mounted volumes (as these are owned by root inside the container).
